# Generated by Django 6.0 on 2026-01-17 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChippingAddress',
            new_name='ShoppingAddress',
        ),
    ]
