# Generated by Django 5.2.10 on 2026-03-13 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_order_is_processed_product_discount_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount_price',
        ),
        migrations.AddField(
            model_name='product',
            name='sale_percent',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
