# Generated by Django 5.2.10 on 2026-01-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_product_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingaddress',
            old_name='cusromer',
            new_name='customer',
        ),
        migrations.RemoveField(
            model_name='shoppingaddress',
            name='state',
        ),
        migrations.AddField(
            model_name='shoppingaddress',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoppingaddress',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shoppingaddress',
            name='address',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shoppingaddress',
            name='city',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shoppingaddress',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='shoppingaddress',
            name='mobile',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
