# Generated by Django 5.2.10 on 2026-01-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_cusromer_shoppingaddress_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingaddress',
            name='name',
        ),
        migrations.AlterField(
            model_name='shoppingaddress',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shoppingaddress',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shoppingaddress',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='shoppingaddress',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shoppingaddress',
            name='mobile',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
