# Generated by Django 5.2.10 on 2026-02-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_order_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingaddress',
            name='name',
            field=models.CharField(default='Guest', max_length=200),
            preserve_default=False,
        ),
    ]
