# Generated by Django 5.2.10 on 2026-02-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_orderitem_complete_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='shoppingaddress',
            name='email',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shoppingaddress',
            name='address',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shoppingaddress',
            name='city',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shoppingaddress',
            name='mobile',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
