# Generated by Django 5.2.10 on 2026-03-03 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_orderitem_complete_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_sub',
        ),
    ]
